### ISSUE TITLE
Trying to execute from a loop

### ISSUE THREAD

**Issue by Nykodemus** [adri326/wombot#10]
Hello, I'm trying to execute the wombot inside a looop, where the script reads a txt file with dozens of prompts and the execute. I used the directions in the section about the module, but I keep getting the error/;

> wombot("random", 3, (data) => {
> ^
> 
> TypeError: wombot is not a function
>     at Object.<anonymous> (C:\Users\06979789902\willbot.js:13:1)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
>     at node:internal/main/run_main_module:17:47

This is my code, I'm trying execute on Anaconda as .js file:

> const wombot = require("wombot");
> 
> function readfile() {
>     var fs = require('fs');
>     var file = fs.readFileSync('prompts.txt', 'utf8');
>     var lines = file.split('\n');
>     for (var i = 0; i < lines.length; i++) {
>         console.log(lines[i]);
>         wombot(lines[i], 3);
>     }
> }
>     
> wombot("random", 3, (data) => {
>     console.log(data.status);
>     }, {
>         final: true, // Download the final image
>         inter: false, // Download the intermediary results,
>         download_dir: "./generated/", // Where to download images
>     }).then(data => {
>         console.log(data.path); // Path of the downloaded file
>     }).catch(err => {
>         console.error(err);
>     });

**Comment by adri326** [comment]
Ah, that was why the main pointed to `index.js` instead of `cli.js`; that's on me, I introduced that bug with https://github.com/adri326/wombot/commit/753f4ac1570d6a479e51951967094d72fc97c93e

**Comment by adri326** [comment]
Alright, version `1.4.2` has the issue fixed, iirc `npm` doesn't update git dependencies by default, so you need to force its hand with `npm i wombot`

**Comment by Nykodemus** [comment]
thanks!
