### ISSUE TITLE
Better explanation for identify_key (Originally 'how to get the "identify_key"?')

### ISSUE THREAD

**Issue by edstoica** [adri326/wombot#2]
hello,
thank you for sharing this project! I really like to get it to work ;)
So, can you please explain (for beginners) how to get the "identify_key"?

i see in the secret.json file, it says:
`the key used by wombo.art to identify themselves on google, use F12 to find it: every request to googleapis.com ends with ...?key=THIS_VALUE`

but when I hit F12 on the "https://app.wombo.art/" website, I see no code with "?key="...

thank you in advance.

**Comment by adri326** [comment]
The request is made when the page is loaded, so you should reload it after opening the F12 menu. Among the first requests there should be one to `https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=...`, with the `identify_key` in it. I really wish I could make the key public but I can't tell if they genuinely meant to have it public or not.

I will update the description of the key to make it more accessible, though

**Comment by edstoica** [comment]
thank you for the help!
For other users I would like to add that you have to **click the "network"-tab after hitting F12**, so you see the googleapi request.

So far, it works perfect.
I wrote a quick windows-batchfile that processes a given .txt file line by line. (delay of 5 seconds after each download)
you find the code attached.

thank you again
[wombot-process-list.zip](https://github.com/adri326/wombot/files/7786247/wombot-process-list.zip)


.

**Comment by adri326** [comment]
I'd keep this open for a tad bit until I can get to do the better explanation. Regarding your script, I'd see it more welcome in a gist or a separate repository/fork, which I can link to from this repository, alongside [Elliot's fork](https://github.com/ElliotRoe/wombot) and other usages of the API

**Comment by edstoica** [comment]
ok, I promise to improve my git knowledge ;)
