### ISSUE TITLE
[bug] crash before finishing download

### ISSUE THREAD

**Issue by leopoldhub** [adri326/wombot#3]
Hi, 
The app works great except that once all images are generated, it crashes before ending downloads... :/

Here are the logs:

```
1: progress (23/24)
2: progress (22/24)
3: progress (21/24)
4: progress (21/24)
0: progress (23/24)
1: progress (23/24)
2: progress (23/24)
3: progress (23/24)
4: progress (23/24)
0: progress (24/24)
1: progress (24/24)
2: progress (24/24)
3: progress (23/24)
4: progress (23/24)
0: generated (24/24)
1: generated (24/24)
2: generated (24/24)
3: progress (24/24)
4: progress (24/24)
3: generated (24/24)
4: generated (24/24)
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -71,
  code: 'EPROTO',
  syscall: 'write'
}
```

I hope you can do something for it,
Great work!

**Comment by leopoldhub** [comment]
the running command is 
`node cli.js "Steins;Gate" 1 --times 5 --inter`

**Comment by adri326** [comment]
I don't seem to be able to reproduce it on my end, could I get your node version (`node --version`) and OS version (`uname -a`)?

While I'm at it, does it crash with a simple request (for instance `node cli.js "Steins;Gate" 1`)?

**Comment by leopoldhub** [comment]
It seems to crash only with --inter on my side... 
node version: `v16.13.0`
os: `Linux burn-ubuntu 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
